# This is a basic workflow to help you get started with Actions

name: CI Windows

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  idris1:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: download and install idris1
        run: |
          Invoke-WebRequest -OutFile idris.exe -Uri https://neon.se/idris/idris-1.3.3-win64.exe
          ./idris.exe
          ls

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: install npm dependencies
        run: npm ci

      - name: test with idris 1
        run: npm run test
      # - name: test with idris 2
      #   run: nix-shell ./nix/idris2 --run "npm run test"
